---
- name: update apt
  apt:
    update_cache: yes
  
- name: upgrade apt
  apt:
    upgrade: yes

- name: install nodejs repo for version 13x
  shell: |
    curl https://deb.nodesource.com/setup_13.x | sudo bash -
  args:
    executable: /bin/bash  

- name: install nodejs with apt
  apt:
    update_cache: yes
    name: nodejs

- name: install pm2
  shell: npm install pm2 -g 