---
- name: update apt
  apt:
    update_cache: yes
  
- name: upgrade apt
  apt:
    upgrade: yes

- name: install nodejs with apt
  apt:
    update_cache: yes
    pkg: 
      - nodejs
      - python3

- name: install npm with apt
  apt:
    update_cache: yes
    name: npm

- name: install pm2
  command: npm install pm2 -g 