---
- name: update apt
  apt:
    update_cache: yes
  
- name: upgrade apt
  apt:
    upgrade: yes

- name: install nodejs 
  shell: |
    curl https://deb.nodesource.com/setup_13.x | sudo bash -
    sudo apt install nodejs -y

- name: install pm2
  command: npm install pm2 -g 