---
- name: update apt
  apt:
    update_cache: yes
  
- name: upgrade apt
  apt:
    upgrade: yes

- name: install nodejs repo for version 13x
  shell: |
    curl https://deb.nodesource.com/setup_13.x -o setup_13x.sh
    chmod +x setup_13x.sh
    setup_13x.sh
  args:
    executable: /bin/bash
    

- name: install nodejs with apt
  apt:
    update_cache: yes
    name: nodejs

- name: install pm2
  shell: npm --version
  register: check-npm

- name: print npm output
  debug: 
    var: check-npm

- name: install pm2
  shell: npm install pm2 -g 