---
- name: Create a directory for the project 
  file:
    path: /home/ubuntu/node_project
    state: directory
    mode: '0755'

- name: Extract backend files into /etc/node_project
  unarchive:
    src: /tmp/artifact.tar.gz 
    dest: /home/ubuntu/node_project
  register: untar

- name: Remove tar file 
  ansible.builtin.file:
    path: /home/ubuntu/artifact.tar.gz
    state: absent

- name: serve file
  shell: |
    npm install
    pm2 stop default
    pm2 start npm -- start
  args:
    chdir: /home/ubuntu/node_project
 