---
- name: Create a directory for the project 
  file:
    path: /etc/node_project
    state: directory
    mode: '0755'
  register: create_dir



- name: Extract backend files into /etc/node_project
  unarchive:
    src: /tmp/artifact.tar.gz 
    dest: /etc/node_project
  register: untar

- debug:
    var: untar

- name: serve file
  shell: |
    cd backend
    npm install
    pm2 stop default
    pm2 start npm -- start
  args:
    chdir: /etc/node_project
  register: serve

- debug:
    var: serve