version: 2.1
executors:
  node:
    docker:
      - image: circleci/node:13.8.0
orbs: 
  slack: circleci/slack@4.10.1

# use yaml syntax to reduce redundancy when defining context 
default-context: &default-context
  context:
    - udacity-project-3

jobs:
  build-frontend:
    executor: node
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: Build front-end
          command: |
            cd frontend
            npm install
            npm run build
      - save_cache:
          paths: [frontend/node_modules]
          key: frontend-build
      - slack/notify:
          channel: $SLACK_DEFAULT_CHANNEL
          event: fail
          template: basic_fail_1

  build-backend:
    executor: node
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:
          name: Back-end build
          command: |
            cd backend
            npm install
            npm run build
      - save_cache:
          paths: [backend/node_modules]
          key: backend-build
      - slack/notify:
          channel: $SLACK_DEFAULT_CHANNEL
          event: fail
          template: basic_fail_1

  test-frontend:
      executor: node
      steps:
        - checkout
        - restore_cache:
            keys: [frontend-build]
        - run:
            name: test 
            command: |
              cd backend
              npm install
              npm run test 
        - slack/notify:
          channel: $SLACK_DEFAULT_CHANNEL
          event: fail
          template: basic_fail_1
                
  test-backend:
    executor: node
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:
          name: test
          command: |
            cd frontend
            npm install
            npm run test
      - slack/notify:
          channel: $SLACK_DEFAULT_CHANNEL
          event: fail
          template: basic_fail_1
  
  scan-frontend:
    executor: node
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          command: |
            cd frontend
            npm install
            npm audit fix --audit-level=critical --force
            npm audit --audit-level=critical
      - slack/notify:
          channel: $SLACK_DEFAULT_CHANNEL
          event: fail
          template: basic_fail_1

  scan-backend:
    executor: node
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:
          command: |
            cd backend
            npm install
            npm audit fix --audit-level=critical --force
            npm audit fix --force
            npm audit --audit-level=critical
      - slack/notify:
          channel: $SLACK_DEFAULT_CHANNEL
          event: fail
          template: basic_fail_1

workflows:
  my_workflow:
    jobs:
      - build-frontend:
          <<: *default-context
      - build-backend:
          <<: *default-context
      - test-frontend:
          <<: *default-context
          requires: [build-frontend]
      - test-backend:
          <<: *default-context
          requires: [build-backend]
      - scan-frontend:
          <<: *default-context
          requires: [build-frontend]
      - scan-backend:
          <<: *default-context
          requires: [build-backend]
